services:
  sz41-nav:
    build: .
    container_name: sz41-nav
    restart: unless-stopped
    ports:
      - "8900:80"
    volumes:
      - ./output/index.html:/usr/share/nginx/html/index.html
    networks:
      - sz41-network

networks:
  sz41-network:
    external: false
